apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-service
  namespace: hsys
spec:
  replicas: 1
  selector:
    matchLabels: { app: public-service }
  template:
    metadata:
      labels: { app: public-service }
    spec:
      containers:
        - name: public
          image: andrewscl/public-service:0.0.1
          ports: [ { containerPort: 8080 } ]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }